fix: update info docs and polices - JAVA files added Copyright info in header - Added CODE_OF_CONDUCT.md - Added CONTRIBUTING.md - Added ISSUE_TEMPLATES and PULL_REQUEST_TEMPLATE - Updated build and release workflows - Updated pom.xml
Signed-off-by: Joel Hanson <joelhanson025@gmail.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,17 +1,18 @@
 name: Build and analyze
+
 on:
   push:
     branches:
       - main
-      - develop
-      - dependabot/**
   pull_request:
     types: [opened, synchronize, reopened]
+
 jobs:
   build:
     name: Build and analyze
     runs-on: ubuntu-24.04
     steps:
+
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
@@ -44,20 +45,41 @@ jobs:
           echo "default-key ${KEY_ID}" >> ~/.gnupg/gpg.conf
           echo "use-agent" >> ~/.gnupg/gpg.conf
 
-      - name: Build and analyze
+      - name: Get java-version
+        run: |
+          BUILD_VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
+          echo "VERSION=$BUILD_VERSION" >> $GITHUB_ENV
+
+      - name: Build compile test and analyze
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=darioajr_java-fix-to-avro
 
-      - name: Run Tests
-        run: mvn test
-
       - name: Run Checkstyle
-        run: mvn checkstyle:check
+        run: mvn -B checkstyle:check
 
       - name: Upload coverage reports to Codecov
         uses: codecov/codecov-action@v5
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           fail_ci_if_error: false
+
+  verify-commits:
+    name: Verify Commits
+    runs-on: ubuntu-24.04
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
+      with:
+        ref: ${{ github.event.pull_request.head.sha }}
+        fetch-depth: 0
+
+    - name: Verify Signed-off-by
+      run: |
+        for commit in $(git rev-list --no-merges HEAD^..HEAD); do
+          if ! git log -1 --format=%B "$commit" | grep -q "^Signed-off-by: "; then
+            echo "Commit $commit is missing Signed-off-by line."
+            exit 1
+          fi
+        done
